### ISSUE TITLE
Pinch to zoom in - zoom out not working

### ISSUE THREAD

**Issue by dragonlord2025** [netless-io/netless-android-whiteboard#12]
I am doing this but the whiteboard zoom in - zoom out not working consistently. Any idea? On first install it works then it stops working. @BlackHole1 @alwaysmavs @leavesster @a1528zhang 

 object : Promise<Room> {

            override fun then(room: Room?) {
                /*val cam = CameraConfig()
                val mWidth: Double = resources.displayMetrics.widthPixels + 0.0
                val mHeight: Double = resources.displayMetrics.heightPixels + 0.0
                cam.centerX = 0.0
                cam.centerY = 0.0
                cam?.scale
                //room?.moveCamera(cam)*/

                runOnUiThread {
                    val config = RectangleConfig(-480.0, -270.0, 960.0, 540.0)
                    config.animationMode = AnimationMode.Immediately
                    room!!.moveCameraToContainer(config)
                    //room.zoomChange(3.0)
                }
            }

            override fun catchEx(error: SDKError?) {
                val i = 0
               
            }
        })

**Comment by leavesster** [comment]
Did you move whiteboard's vision (use two fingers to move coordinate or change scale) after first invoke?
This api just move to the special coordinate and keep default scale. If you didn't change any vision，it's maybe seem not works.

**Comment by dragonlord2025** [comment]
Yeah, I discovered that. What I figured out was when the I join whiteboard before the other person joins then that time zoom in zoom out won't' work but I can see part of the whiteboard. When I join whiteboard after the other person joins then zoom in, zoom out it works fine. Hopefully it this issue will be solved in the next SDK version.

**Comment by leavesster** [comment]
> Yeah, I discovered that. What I figured out was when the I join whiteboard before the other person joins then that time zoom in zoom out won't' work but I can see part of the whiteboard. When I join whiteboard after the other person joins then zoom in, zoom out it works fine. Hopefully it this issue will be solved in the next SDK version.

So you can't zoom in zoom out when there is no person in whiteboard ?  
It seems inconsistency with what was said at the beginning

**Comment by leavesster** [comment]
It may be some misuse, or is fixed in current SDK version.

The current project contains too much business code and is no longer being updated.

you can use https://github.com/duty-os/white-demo-android to test(We have not reproduced this bug)
or update this repo's whiteboard SDK to 2.9.14 (It has some break change, you need read https://developer.netless.link/docs/android/migration/android-2.9.0/ ).
